const HOME_SCREEN = "HOME_SCREEN";
const LOBBY_WAITING = "LOBBY_WAITING";
const IN_GAME = "IN_GAME";
const GAME_OVER = "GAME_OVER";

const DEFAULT_COLOR = "#000000";

const CANVAS_WIDTH = 588;
const CANVAS_HEIGHT = 412;

export {
  HOME_SCREEN,
  LOBBY_WAITING,
  IN_GAME,
  GAME_OVER,
  DEFAULT_COLOR,
  CANVAS_WIDTH,
  CANVAS_HEIGHT,
};
